# -*- coding: utf-8 -*-
"""Projeto_knowledge_graphs.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-6rL3fOTese_GHGHHNE3cDF6UIegDF5u
"""

import networkx as nx
import matplotlib.pyplot as plt

class NBAKnowledgeGraph():
  def __init__(self):
    #Inicialização dos nós e das arestas
    self.nodes = {}
    self.edges = {}

  def adicionar_no(self, id_no, tipo, propriedades):
    #Se o id já existir ele não é adicionado
    if id_no in self.nodes:
      print(f"ERRO: O id {id_no} já existe!")
      return False
    #Cria uma cópia do dicionário de propriedades e adiciona 'tipo' ao dicionário
    dados_do_no = propriedades.copy()
    dados_do_no['tipo'] = tipo
    #Guarda o nó no grafo utilizando o identificador 'id_no'
    self.nodes[id_no] = dados_do_no
    #Ele cria o nó e também cria a lista vazia de relações para ser preenchida posteriormente
    self.edges[id_no] = []

    print(f"Nó {id_no} adicionado!")

    return True

  def adicionar_relacionamento(self, origem, destino, relacao, propriedades=None):
    #Se não for passado um parâmetro adicional, ele retorna um dicionário vazio
    if propriedades is None:
      propriedades = {}

    #Se tanto o nó de origem quanto o de destino existirem, a relação é adicionada na aresta
    if origem in self.nodes and destino in self.nodes:
      aresta = {
          "relacao": relacao,
          "destino": destino,
          "propriedades": propriedades
      }
      self.edges[origem].append(aresta)
      print(f"A relação {origem} -> {relacao} -> {destino} foi adicionada!")
      return True
    else:
      print(f"A origem {origem} e/ou destino {destino} não existe!")
      return False

  #Parte das buscas
  def buscar_nos_por_tipo(self, tipo):
    #Lista vazia que armazenará o resultado encontrado
    resultado = []
    #Percorre todos os nós procurando se algum tipo é encontrado
    #Adiciona o id do nó em resultado
    for id_no, propriedades in self.nodes.items():
        if propriedades.get("tipo") == tipo:
            resultado.append(id_no)
    return resultado

  #Função de busca direta, ou seja procura diretamente o nó que você quer e retorna
  def buscar_nos_por_id(self, id_no):
    return self.nodes.get(id_no, None)

  #Aqui eu imprimo todas as arestas presentes, ou seja todas as relações
  def imprimir_arestas(self):
    for origem, arestas in self.edges.items():
        for a in arestas:
            print(origem, ",", a["relacao"], ",", a["destino"], a["propriedades"])

  #Nessa primeira função eu mostro todas as arestas que tem a relação que passei quando chamei a função
  def imprimir_arestas_de_tipo(self, tipo_relacao):
    for origem, arestas in self.edges.items():
        for a in arestas:
            if a["relacao"] == tipo_relacao:
                print(origem, ",", a["relacao"], ",", a["destino"], a["propriedades"])

  #Já nessa função se busca e retorna as arestas para caso seja necessário usar essa informação
  def buscar_arestas_de_origem(self, origem):
    return self.edges.get(origem, [])

  #Funções de remoção
  def remover_no(self, id_no):
    if id_no not in self.nodes:
        return False
    # remove arestas saindo do nó
    self.edges.pop(id_no, None)
    # remove arestas que chegam no nó
    for origem, arestas in self.edges.items():
        self.edges[origem] = [a for a in arestas if a["destino"] != id_no]
    # remove o nó
    del self.nodes[id_no]
    return True

  def remover_relacionamento(self, origem, relacao, destino):
    if origem not in self.edges:
        return False
    #Armazena quantas arestas saem da origem
    antes = len(self.edges[origem])
    #Adiciona todas as arestas da origem se elas não coincidirem em destino e relação com a que se quer remover
    self.edges[origem] = [
        a for a in self.edges[origem]
        if not (a["destino"] == destino and a["relacao"] == relacao)
    ]
    #Se o tamanho diminuiu então a aresta foi removida
    return len(self.edges[origem]) < antes

  #Função de carregar os grafos
  def carregar_times_e_arenas(self):
    #Times importantes para o mini-mundo
    self.adicionar_no("Cavaliers", "Team", {"Cidade": "Cleveland"})
    self.adicionar_no("Warriors", "Team", {"Cidade": "Oakland"})
    self.adicionar_no("Celtics", "Team", {"Cidade": "Boston"})
    self.adicionar_no("Thunder", "Team", {"Cidade": "Oklahoma"})
    #Arenas onde foram disputados os jogos
    self.adicionar_no("QuickenLoansArena", "Arena", {"Cidade": "Cleveland"})
    self.adicionar_no("OracleArena", "Arena", {"Cidade": "Oakland"})

  def carregar_finais(self):
    #Ano das finais
    self.adicionar_no("Finais_2015", "Finals", {"Temporada": "2014-2015", "Resultado": "4-2", "Vencedor": "Warriors", "MVP": "Andre Iguodala"})
    self.adicionar_no("Finais_2016", "Finals", {"Temporada": "2015-2016", "Resultado": "4-3", "Vencedor": "Cavaliers", "MVP": "LeBron James"})
    self.adicionar_no("Finais_2017", "Finals", {"Temporada": "2016-2017", "Resultado": "4-1", "Vencedor": "Warriors", "MVP": "Kevin Durant"})
    self.adicionar_no("Finais_2018", "Finals", {"Temporada": "2017-2018", "Resultado": "4-0", "Vencedor": "Warriors", "MVP": "Kevin Durant"})

  def carregar_jogadores(self):
    #Jogadores do cavs
    self.adicionar_no("LeBron_James", "Player", {"Nome": "LeBron James", "Número": "23", "Posição": "SF", })
    self.adicionar_no("Kyrie_Irving", "Player", {"Nome": "Kyrie Irving", "Número": "2", "Posição": "PG"})
    self.adicionar_no("Kevin_Love", "Player", {"Nome": "Kevin Love", "Número": "0", "Posição": "PF"})
    self.adicionar_no("J.R._Smith", "Player", {"Nome": "J.R. Smith", "Número": "5", "Posição": "SG"})
    self.adicionar_no("Tristan_Thompson", "Player", {"Nome": "Tristan Thompson", "Número": "13", "Posição": "C"})
    #Jogadores do gsw
    self.adicionar_no("Stephen_Curry", "Player", {"Nome": "Stephen Curry", "Número": "30", "Posição": "PG"})
    self.adicionar_no("Klay_Thompson", "Player", {"Nome": "Klay Thompson", "Número": "11", "Posição": "SG"})
    self.adicionar_no("Draymond_Green", "Player", {"Nome": "Draymond Green", "Número": "23", "Posição": "PF"})
    self.adicionar_no("Andre_Iguodala", "Player", {"Nome": "Andre Iguodala", "Número": "9", "Posição": "SF"})
    self.adicionar_no("Kevin_Durant", "Player", {"Nome": "Kevin Durant", "Número": "35", "Posição": "SF"})
    self.adicionar_no("Anderson_Varejao", "Player", {"Nome": "Anderson Varejão", "Número": "18", "Posição": "C"})

  def carregar_tecnicos(self):
    #Os dois técnicos que o cavs teve e o técnido do warriors
    self.adicionar_no("David_Blatt", "Coach", {"Nome": "David Blatt"})
    self.adicionar_no("Tyronn_Lue", "Coach", {"Nome": "Tyronn Lue"})
    self.adicionar_no("Steve_Kerr", "Coach", {"Nome": "Steve Kerr"})

  def carregar_eventos_historicos(self):
    self.adicionar_no("Lesao_Kyrie_Jogo1", "Evento_historico", {"Descrição": "Kyrie Irving lesiona o joelho no jogo 1 e perde o restante das finais", "Jogo": "1", "Temporada": "2014-2015"})
    self.adicionar_no("Iguodala_titular_jogo4", "Evento_historico", {"Descrição": "Iguodala vira titular em uma nova estratégia de small ball criada pelo coach Kerr", "Jogo": "4", "Temporada": "2014-2015"})
    self.adicionar_no("Jogo5_2016_41pts_LeBron_Kyrie", "Evento_historico", {"Descrição": "Jogo histórico que ambos os jogadores marcam 41 pontos cada", "Jogo": "5", "Temporada": "2015-2016"})
    self.adicionar_no("Transferencia_Durant", "Evento_historico", {"Descrição": "Transferência que abalou a NBA e acabou a competitividade da liga por 2 anos", "Ano": "2017"})

  #Relacionamentos
  def carregar_relacionamentos(self):
    #Jogadores do cavs
    self.adicionar_relacionamento("LeBron_James", "Cavaliers", "JOGOU_POR", {"Temporadas": "2014-2018"})
    self.adicionar_relacionamento("Kyrie_Irving", "Cavaliers", "JOGOU_POR", {"Temporadas": "2011-2017"})
    self.adicionar_relacionamento("Kyrie_Irving", "Celtics", "JOGOU_POR", {"Temporadas": "2017-2019"})
    self.adicionar_relacionamento("J.R._Smith", "Cavaliers", "JOGOU_POR", {"Temporadas": "2015-2019"})
    self.adicionar_relacionamento("Tristan_Thompson", "Cavaliers", "JOGOU_POR", {"Temporadas": "2011-2020"})
    self.adicionar_relacionamento("Kevin_Love", "Cavaliers", "JOGOU_POR", {"Temporadas": "2014-2023"})
    self.adicionar_relacionamento("Anderson_Varejao", "Cavaliers", "JOGOU_POR", {"Temporadas": "2004-2016"})
    #Jogadores do gsw
    self.adicionar_relacionamento("Anderson_Varejao", "Warriors", "JOGOU_POR", {"Temporadas": "2016-2017"})
    self.adicionar_relacionamento("Kevin_Durant", "Thunder", "JOGOU_POR", {"Temporadas": "2008-2016"})
    self.adicionar_relacionamento("Kevin_Durant", "Warriors", "JOGOU_POR", {"Temporadas": "2016-2019"})
    self.adicionar_relacionamento("Klay_Thompson", "Warriors", "JOGOU_POR", {"Temporadas": "2011-ATUAL"})
    self.adicionar_relacionamento("Andre_Iguodala", "Warriors", "JOGOU_POR", {"Temporadas": "2013-2019"})
    self.adicionar_relacionamento("Stephen_Curry", "Warriors", "JOGOU_POR", {"Temporadas": "2009-ATUAL"})
    self.adicionar_relacionamento("Draymond_Green", "Warriors", "JOGOU_POR", {"Temporadas": "2012-ATUAL"})
    #Técnicos
    self.adicionar_relacionamento("David_Blatt", "Cavaliers", "TREINOU", {"Temporadas": "2014-2016"})
    self.adicionar_relacionamento("Tyronn_Lue", "Cavaliers", "TREINOU", {"Temporadas": "2016-2018"})
    self.adicionar_relacionamento("Steve_Kerr", "Warriors", "TREINOU", {"Temporadas": "2014-ATUAL"})
    #Times que participaram das finais
    self.adicionar_relacionamento("Cavaliers", "QuickenLoansArena", "MANDA_JOGOS_EM")
    self.adicionar_relacionamento("Warriors", "OracleArena", "MANDA_JOGOS_EM")

    self.adicionar_relacionamento("Cavaliers", "Finais_2015", "DISPUTOU", {"Resultado_time": "Derrota", "Placar": "2-4"})
    self.adicionar_relacionamento("Cavaliers", "Finais_2016", "DISPUTOU", {"Resultado_time": "Vitória", "Placar": "4-3"})
    self.adicionar_relacionamento("Cavaliers", "Finais_2017", "DISPUTOU", {"Resultado_time": "Derrota", "Placar": "1-4"})
    self.adicionar_relacionamento("Cavaliers", "Finais_2018", "DISPUTOU", {"Resultado_time": "Derrota", "Placar": "0-4"})

    self.adicionar_relacionamento("Warriors", "Finais_2015", "DISPUTOU", {"Resultado_time": "Vitória", "Placar": "4-2"})
    self.adicionar_relacionamento("Warriors", "Finais_2016", "DISPUTOU", {"Resultado_time": "Derrota", "Placar": "3-4"})
    self.adicionar_relacionamento("Warriors", "Finais_2017", "DISPUTOU", {"Resultado_time": "Vitória", "Placar": "4-1"})
    self.adicionar_relacionamento("Warriors", "Finais_2018", "DISPUTOU", {"Resultado_time": "Vitória", "Placar": "4-0"})

    #MVPs de cada final
    self.adicionar_relacionamento("Andre_Iguodala", "Finais_2015", "MVP_DE")
    self.adicionar_relacionamento("LeBron_James", "Finais_2016", "MVP_DE")
    self.adicionar_relacionamento("Kevin_Durant", "Finais_2017", "MVP_DE")
    self.adicionar_relacionamento("Kevin_Durant", "Finais_2018", "MVP_DE")

    #Grandes momentos
    #Lesão do Kyrie
    self.adicionar_relacionamento("Kyrie_Irving", "Lesao_Kyrie_Jogo1", "SOFREU_LESAO")
    self.adicionar_relacionamento("Lesao_Kyrie_Jogo1", "Finais_2015", "IMPACTOU_RESULTADO")
    self.adicionar_relacionamento("Lesao_Kyrie_Jogo1", "OracleArena", "OCORREU_EM")
    #Ajuste técnico decisivo
    self.adicionar_relacionamento("Andre_Iguodala", "Iguodala_titular_jogo4", "VIROU_TITULAR_EM")
    self.adicionar_relacionamento("Steve_Kerr", "Iguodala_titular_jogo4", "REALIZOU_AJUSTE")
    self.adicionar_relacionamento("Iguodala_titular_jogo4", "Finais_2015", "MUDOU_RUMO_DE")
    #Jogo histórico de 41 pontos
    self.adicionar_relacionamento("LeBron_James", "Jogo5_2016_41pts_LeBron_Kyrie", "PONTUACAO_HISTORICA", {"Pontos": 41})
    self.adicionar_relacionamento("Kyrie_Irving", "Jogo5_2016_41pts_LeBron_Kyrie", "PONTUACAO_HISTORICA", {"Pontos": 41})
    self.adicionar_relacionamento("Jogo5_2016_41pts_LeBron_Kyrie", "Finais_2016", "EVITOU_ELIMINACAO")
    self.adicionar_relacionamento("Jogo5_2016_41pts_LeBron_Kyrie", "OracleArena", "OCORREU_EM")

    #A transferência que quebrou a NBA
    self.adicionar_relacionamento("Kevin_Durant", "Transferencia_Durant", "PROTAGONIZOU")
    self.adicionar_relacionamento("Transferencia_Durant", "Thunder", "SAIU_DE")
    self.adicionar_relacionamento("Transferencia_Durant", "Warriors", "MUDOU_PARA")

  def carregar_dados(self):
    self.carregar_times_e_arenas()
    self.carregar_jogadores()
    self.carregar_tecnicos()
    self.carregar_eventos_historicos()
    self.carregar_finais()
    self.carregar_relacionamentos()

  #EXTRA: Parte do código para visualização dos grafos
  def para_networkx(self):
    G = nx.DiGraph()
    # nós
    for nid, props in self.nodes.items():
        G.add_node(nid, **props)
    # arestas
    for origem, arestas in self.edges.items():
        for a in arestas:
            G.add_edge(origem, a["destino"], relacao=a["relacao"], **a["propriedades"])
    return G

  def desenhar(self):
      G = self.para_networkx()
      plt.figure(figsize=(12, 8))
      pos = nx.spring_layout(G, k=0.5, seed=42)
      nx.draw(G, pos, with_labels=True, node_size=800, font_size=8, arrows=True)
      edge_labels = nx.get_edge_attributes(G, "relacao")
      nx.draw_networkx_edge_labels(G, pos, edge_labels=edge_labels, font_size=6)
      plt.show()

  def subgrafo_por_nos(self, lista_nos):
    sub = NBAKnowledgeGraph()
    for nid in lista_nos:
        if nid in self.nodes:
            props = self.nodes[nid].copy()
            tipo = props.pop("tipo")
            sub.adicionar_no(nid, tipo, props)
    for origem in lista_nos:
        for a in self.edges.get(origem, []):
            if a["destino"] in lista_nos:
                sub.adicionar_relacionamento(origem, a["destino"], a["relacao"], a["propriedades"])
    return sub


g1 = NBAKnowledgeGraph()

g1.carregar_dados()
g1.imprimir_arestas_de_tipo("DISPUTOU")
print(g1.buscar_arestas_de_origem("LeBron_James"))
print(g1.buscar_nos_por_id("LeBron_James"))
g1.remover_no("LeBron_James")
print(g1.buscar_arestas_de_origem("LeBron_James"))
g1.remover_relacionamento("Kevin_Durant", "MVP_DE", "Finais_2018")

g1.desenhar()
nos_2015 = [
    "Finais_2015","Cavaliers","Warriors",
    "LeBron_James","Kyrie_Irving", "Anderson_Varejao", "Stephen_Curry",
    "Andre_Iguodala","Lesao_Kyrie_Jogo1","Iguodala_titular_jogo4",
    "QuickenLoansArena","OracleArena"]

nos_2016 = [
    "Finais_2016",
    "Cavaliers", "Warriors",
    "LeBron_James", "Kyrie_Irving", "Kevin_Love",
    "Stephen_Curry", "Klay_Thompson", "Draymond_Green",
    "Jogo5_2016_41pts_LeBron_Kyrie",
    "QuickenLoansArena", "OracleArena"]

nos_2017 = [
    "Finais_2017",
    "Cavaliers", "Warriors",
    "LeBron_James", "Kyrie_Irving", "Kevin_Love",
    "Stephen_Curry", "Klay_Thompson", "Draymond_Green", "Kevin_Durant",
    "QuickenLoansArena", "OracleArena"]

nos_2018 = [
    "Finais_2018",
    "Cavaliers", "Warriors",
    "LeBron_James", "Kevin_Love",
    "Stephen_Curry", "Klay_Thompson", "Draymond_Green", "Kevin_Durant",
    "QuickenLoansArena", "OracleArena"]


sub_2015 = g1.subgrafo_por_nos(nos_2015)
sub_2015.desenhar()

sub_2016 = g1.subgrafo_por_nos(nos_2016)
sub_2016.desenhar()

sub_2017 = g1.subgrafo_por_nos(nos_2017)
sub_2017.desenhar()

sub_2018 = g1.subgrafo_por_nos(nos_2018)
sub_2018.desenhar()

